# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models
import django.contrib.postgres.fields
import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0006_require_contenttypes_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(null=True, verbose_name='last login', blank=True)),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=30, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.', 'invalid')], help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', unique=True, verbose_name='username')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name', blank=True)),
                ('last_name', models.CharField(max_length=30, verbose_name='last name', blank=True)),
                ('email', models.EmailField(max_length=254, verbose_name='email address', blank=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('credit_name', models.CharField(help_text=b'Full name of user as listed as a credit on content.', max_length=75, blank=True)),
                ('title', models.CharField(help_text=b'Professional title', max_length=100, blank=True)),
                ('phone', models.CharField(max_length=20, blank=True)),
                ('bio', models.TextField(help_text=b'Short bio.', blank=True)),
                ('expertise', django.contrib.postgres.fields.ArrayField(default=list, help_text=b'Array of user skills and beats to filter/search by.', size=None, base_field=models.CharField(max_length=100), blank=True)),
                ('profile_photo', models.ImageField(upload_to=b'users', blank=True)),
                ('facebook', models.CharField(max_length=250, blank=True)),
                ('twitter', models.CharField(max_length=250, blank=True)),
                ('linkedin', models.CharField(max_length=250, blank=True)),
                ('instagram', models.CharField(max_length=250, blank=True)),
                ('snapchat', models.CharField(max_length=250, blank=True)),
                ('vine', models.CharField(max_length=250, blank=True)),
                ('website', models.CharField(max_length=250, blank=True)),
                ('groups', models.ManyToManyField(related_query_name='user', related_name='user_set', to='auth.Group', blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', verbose_name='groups')),
            ],
            options={
                'ordering': ['credit_name'],
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('asset_description', models.TextField(help_text=b'What is the asset. (If a photo or graphic, it should be the caption.)', max_length=300, blank=True)),
                ('attribution', models.TextField(help_text=b'The appropriate information for crediting the asset.', max_length=200, blank=True)),
                ('s3_link', models.URLField(help_text=b'The item on S3.', max_length=300)),
                ('asset_type', models.CharField(help_text=b'What kind is the asset.', max_length=20, choices=[(b'PIC', b'Photograph'), (b'GRAPH', b'Graphic'), (b'AUD', b'Audio'), (b'VID', b'Video'), (b'DOC', b'Document')])),
                ('creation_date', models.DateTimeField(help_text=b'When the asset was created.', auto_now_add=True)),
                ('keywords', django.contrib.postgres.fields.ArrayField(default=list, help_text=b'List of keywords for search.', base_field=models.CharField(max_length=100), size=None)),
                ('owner', models.ForeignKey(related_name='asset_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AudioFacet',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(help_text=b'Unique code as needed for ingest sytems. Use as needed', max_length=75, blank=True)),
                ('title', models.TextField(help_text=b'Headline of the audiofacet.')),
                ('excerpt', models.TextField(help_text=b'Excerpt for the audiofacet.', blank=True)),
                ('af_description', models.TextField(help_text=b'Description of the audiofacet.', blank=True)),
                ('content', models.TextField(help_text=b'Content of the audiofacet.', blank=True)),
                ('length', models.IntegerField(help_text=b'Wordcount of the audiofacet.', blank=True)),
                ('keywords', django.contrib.postgres.fields.ArrayField(default=list, help_text=b'List of keywords for search.', base_field=models.CharField(max_length=100), size=None)),
                ('status', models.CharField(help_text=b'Audiofacet status choice.', max_length=25, choices=[(b'DRFT', b'Draft'), (b'PT', b'Pitch'), (b'IP', b'In Progress'), (b'EDT', b'Edit'), (b'RVN', b'Revision'), (b'RDY', b'Ready')])),
                ('due_edit', models.DateTimeField(help_text=b'Due for edit.', blank=True)),
                ('run_date', models.DateTimeField(help_text=b'Planned run date.', blank=True)),
                ('creation_date', models.DateTimeField(help_text=b'Day audiofacet was created.', auto_now_add=True)),
                ('share_note', models.TextField(help_text=b'Information for organizations making a copy of the audiofacet.', blank=True)),
                ('assets', models.ManyToManyField(to='editorial.Asset')),
            ],
            options={
                'ordering': ['creation_date'],
                'verbose_name': 'Audiofacet',
                'verbose_name_plural': 'Audiofacets',
            },
        ),
        migrations.CreateModel(
            name='AudioFacetContributor',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('user_role', models.CharField(help_text=b'What did the user do?', max_length=255)),
                ('audiofacet', models.ForeignKey(to='editorial.AudioFacet')),
                ('user', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AudioFacetCopyDetail',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('new_audiofacet_id', models.SlugField(help_text=b"Id of the story on the copying organization's site.", max_length=15)),
                ('copy_date', models.DateTimeField(help_text=b'Datetime when copy was made.', auto_now_add=True)),
                ('original_audiofacet_id', models.ForeignKey(help_text=b'Original id of the story.', to='editorial.AudioFacet')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('text', models.TextField(help_text=b'The content of the comment.')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommentReadStatus',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('datetime_read', models.DateTimeField(auto_now_add=True)),
                ('has_read', models.BooleanField(default=True)),
                ('comment', models.ForeignKey(to='editorial.Comment')),
                ('user', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('discussion_type', models.CharField(help_text=b'What kind of discussion is it.', max_length=25, choices=[(b'PRI', b'Private Conversation'), (b'SER', b'Series Conversation'), (b'STO', b'Story Conversation'), (b'WF', b'WebFacet Conversation'), (b'PF', b'PrintFacet Conversation'), (b'AF', b'AudioFacet Conversation'), (b'VF', b'VideoFacet Conversation')])),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalAudioFacet',
            fields=[
                ('id', models.IntegerField(verbose_name='ID', db_index=True, auto_created=True, blank=True)),
                ('code', models.CharField(help_text=b'Unique code as needed for ingest sytems. Use as needed', max_length=75, blank=True)),
                ('title', models.TextField(help_text=b'Headline of the audiofacet.')),
                ('excerpt', models.TextField(help_text=b'Excerpt for the audiofacet.', blank=True)),
                ('af_description', models.TextField(help_text=b'Description of the audiofacet.', blank=True)),
                ('content', models.TextField(help_text=b'Content of the audiofacet.', blank=True)),
                ('length', models.IntegerField(help_text=b'Wordcount of the audiofacet.', blank=True)),
                ('keywords', django.contrib.postgres.fields.ArrayField(default=list, help_text=b'List of keywords for search.', base_field=models.CharField(max_length=100), size=None)),
                ('status', models.CharField(help_text=b'Audiofacet status choice.', max_length=25, choices=[(b'DRFT', b'Draft'), (b'PT', b'Pitch'), (b'IP', b'In Progress'), (b'EDT', b'Edit'), (b'RVN', b'Revision'), (b'RDY', b'Ready')])),
                ('due_edit', models.DateTimeField(help_text=b'Due for edit.', blank=True)),
                ('run_date', models.DateTimeField(help_text=b'Planned run date.', blank=True)),
                ('creation_date', models.DateTimeField(help_text=b'Day audiofacet was created.', editable=False, blank=True)),
                ('share_note', models.TextField(help_text=b'Information for organizations making a copy of the audiofacet.', blank=True)),
                ('history_id', models.AutoField(serialize=False, primary_key=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(max_length=1, choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')])),
                ('discussion', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='editorial.Discussion', null=True)),
                ('editor', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('history_user', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical Audiofacet',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPrintFacet',
            fields=[
                ('id', models.IntegerField(verbose_name='ID', db_index=True, auto_created=True, blank=True)),
                ('code', models.CharField(help_text=b'Unique code as needed for ingest sytems. Use as needed', max_length=75, blank=True)),
                ('title', models.TextField(help_text=b'Headline of the printfacet.')),
                ('excerpt', models.TextField(help_text=b'Excerpt from the printfacet.', blank=True)),
                ('pf_description', models.TextField(help_text=b'Description of the printfacet.', blank=True)),
                ('content', models.TextField(help_text=b'Content of the printfacet.', blank=True)),
                ('length', models.IntegerField(help_text=b'Wordcount of the printfacet.', blank=True)),
                ('keywords', django.contrib.postgres.fields.ArrayField(default=list, help_text=b'List of keywords for search.', size=None, base_field=models.CharField(max_length=100), blank=True)),
                ('due_edit', models.DateTimeField(help_text=b'Due for edit.', blank=True)),
                ('run_date', models.DateTimeField(help_text=b'Planned run date.', blank=True)),
                ('creation_date', models.DateTimeField(help_text=b'Day printfacet was created.', editable=False, blank=True)),
                ('share_note', models.TextField(help_text=b'Information for organizations making a copy of the printfacet.')),
                ('history_id', models.AutoField(serialize=False, primary_key=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(max_length=1, choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')])),
                ('discussion', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='editorial.Discussion', null=True)),
                ('editor', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('history_user', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical Printfacet',
            },
        ),
        migrations.CreateModel(
            name='HistoricalVideoFacet',
            fields=[
                ('id', models.IntegerField(verbose_name='ID', db_index=True, auto_created=True, blank=True)),
                ('code', models.CharField(help_text=b'Unique code as needed for ingest sytems. Use as needed', max_length=75, blank=True)),
                ('title', models.TextField(help_text=b'Headline of the videofacet.')),
                ('excerpt', models.TextField(help_text=b'Excerpt from the videofacet.', blank=True)),
                ('vf_description', models.TextField(help_text=b'Description of the videofacet.', blank=True)),
                ('content', models.TextField(help_text=b'Content of the videofacet.', blank=True)),
                ('length', models.IntegerField(help_text=b'Wordcount of the videofacet.', blank=True)),
                ('keywords', django.contrib.postgres.fields.ArrayField(default=list, help_text=b'List of keywords for search.', base_field=models.CharField(max_length=100), size=None)),
                ('status', models.CharField(help_text=b'Videofacet status choice.', max_length=25, choices=[(b'DRFT', b'Draft'), (b'PT', b'Pitch'), (b'IP', b'In Progress'), (b'EDT', b'Edit'), (b'RVN', b'Revision'), (b'RDY', b'Ready')])),
                ('due_edit', models.DateTimeField(help_text=b'Due for edit.', blank=True)),
                ('run_date', models.DateTimeField(help_text=b'Planned run date.', blank=True)),
                ('creation_date', models.DateTimeField(help_text=b'Day videofacet was created.', editable=False, blank=True)),
                ('share_note', models.TextField(help_text=b'Information for organizations making a copy of the videofacet.', blank=True)),
                ('history_id', models.AutoField(serialize=False, primary_key=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(max_length=1, choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')])),
                ('discussion', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='editorial.Discussion', null=True)),
                ('editor', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('history_user', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical Videofacet',
            },
        ),
        migrations.CreateModel(
            name='HistoricalWebFacet',
            fields=[
                ('id', models.IntegerField(verbose_name='ID', db_index=True, auto_created=True, blank=True)),
                ('code', models.CharField(help_text=b'Unique code as needed for ingest sytems. Use as needed', max_length=75, blank=True)),
                ('title', models.TextField(help_text=b'Headline of the Webfacet')),
                ('excerpt', models.TextField(help_text=b'Excerpt from the Webfacet.', blank=True)),
                ('wf_description', models.TextField(help_text=b'Description of the WebFacet.', blank=True)),
                ('content', models.TextField(help_text=b'Content of the webFacet.', blank=True)),
                ('length', models.IntegerField(help_text=b'Wordcount of the WebFacet.', blank=True)),
                ('keywords', django.contrib.postgres.fields.ArrayField(default=list, help_text=b'List of keywords for search.', size=None, base_field=models.CharField(max_length=100), blank=True)),
                ('status', models.CharField(help_text=b'WebFacet status choice.', max_length=25, choices=[(b'DRFT', b'Draft'), (b'PT', b'Pitch'), (b'IP', b'In Progress'), (b'EDT', b'Edit'), (b'RVN', b'Revision'), (b'RDY', b'Ready')])),
                ('due_edit', models.DateTimeField(help_text=b'Due for edit.', blank=True)),
                ('run_date', models.DateTimeField(help_text=b'Planned run date.', blank=True)),
                ('creation_date', models.DateTimeField(help_text=b'Day WebFacet was created.', editable=False, blank=True)),
                ('share_note', models.TextField(help_text=b'Information for organizations making a copy of the webfacet.', blank=True)),
                ('history_id', models.AutoField(serialize=False, primary_key=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(max_length=1, choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')])),
                ('discussion', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='editorial.Discussion', null=True)),
                ('editor', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('history_user', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical Webfacet',
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(help_text=b'The name by which members identify the network.', max_length=75, db_index=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('network_description', models.TextField(help_text=b'Short description of a network.', blank=True)),
                ('logo', models.ImageField(upload_to=b'organizations', blank=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Network',
                'verbose_name_plural': 'Networks',
            },
        ),
        migrations.CreateModel(
            name='NetworkOrganization',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('network', models.ForeignKey(to='editorial.Network')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=75, db_index=True)),
                ('org_description', models.TextField(help_text=b'Short profile of organization.', blank=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('logo', models.ImageField(upload_to=b'organizations', blank=True)),
                ('facebook', models.CharField(max_length=250, blank=True)),
                ('twitter', models.CharField(max_length=250, blank=True)),
                ('website', models.CharField(max_length=250, blank=True)),
                ('owner', models.ForeignKey(related_name='organization_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
        migrations.CreateModel(
            name='PrintFacet',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(help_text=b'Unique code as needed for ingest sytems. Use as needed', max_length=75, blank=True)),
                ('title', models.TextField(help_text=b'Headline of the printfacet.')),
                ('excerpt', models.TextField(help_text=b'Excerpt from the printfacet.', blank=True)),
                ('pf_description', models.TextField(help_text=b'Description of the printfacet.', blank=True)),
                ('content', models.TextField(help_text=b'Content of the printfacet.', blank=True)),
                ('length', models.IntegerField(help_text=b'Wordcount of the printfacet.', blank=True)),
                ('keywords', django.contrib.postgres.fields.ArrayField(default=list, help_text=b'List of keywords for search.', size=None, base_field=models.CharField(max_length=100), blank=True)),
                ('due_edit', models.DateTimeField(help_text=b'Due for edit.', blank=True)),
                ('run_date', models.DateTimeField(help_text=b'Planned run date.', blank=True)),
                ('creation_date', models.DateTimeField(help_text=b'Day printfacet was created.', auto_now_add=True)),
                ('share_note', models.TextField(help_text=b'Information for organizations making a copy of the printfacet.')),
                ('assets', models.ManyToManyField(to='editorial.Asset')),
            ],
            options={
                'ordering': ['creation_date'],
                'verbose_name': 'Printfacet',
                'verbose_name_plural': 'Printfacets',
            },
        ),
        migrations.CreateModel(
            name='PrintFacetContributor',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('user_role', models.CharField(help_text=b'What did the user do?', max_length=255)),
                ('printfacet', models.ForeignKey(to='editorial.PrintFacet')),
                ('user', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrintFacetCopyDetail',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('new_printfacet_id', models.SlugField(help_text=b"Id of the story on the copying organization's site.", max_length=15)),
                ('copy_date', models.DateTimeField(help_text=b'Datetime when copy was made.', auto_now_add=True)),
                ('original_printfacet_id', models.ForeignKey(help_text=b'Original id of the story.', to='editorial.PrintFacet')),
                ('partner', models.ForeignKey(help_text=b'Organization that made the copy.', to='editorial.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateDiscussion',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('discussion', models.ForeignKey(to='editorial.Discussion')),
                ('users', models.ManyToManyField(related_name='private_discussion_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(help_text=b'The name identifying the series.', max_length=75)),
                ('series_description', models.TextField(help_text=b'Short description of a series.', blank=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('sensitivity', models.BooleanField(default=False, help_text=b'Is a series sensitive, for limited viewing?')),
                ('share', models.BooleanField(default=False, help_text=b'The series is being shared with a network.')),
                ('collaborate', models.BooleanField(default=False, help_text=b'The series is being collaborated on with a network.')),
                ('archived', models.BooleanField(default=False, help_text=b'Is the content no longer active and needed?')),
                ('assets', models.ManyToManyField(help_text=b'', to='editorial.Asset', blank=True)),
                ('collaborate_with', models.ManyToManyField(help_text=b'Network ids that a series is open to collaboration with.', related_name='series_collaborated_with_network', to='editorial.Network', blank=True)),
                ('discussion', models.ForeignKey(help_text=b',', to='editorial.Discussion')),
                ('owner', models.ForeignKey(related_name='series_owner', to=settings.AUTH_USER_MODEL, help_text=b'The user that created the series.')),
                ('share_with', models.ManyToManyField(help_text=b'Network ids that a series is shared with.', related_name='series_shared_with_network', to='editorial.Network', blank=True)),
                ('team', models.ManyToManyField(help_text=b'User contributing to the series.', related_name='series_team_member', to=settings.AUTH_USER_MODEL, blank=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Series',
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.CreateModel(
            name='SeriesCopyDetail',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('partner_series_id', models.SlugField(help_text=b"Id of the series on the copying organization's site.", max_length=15)),
                ('copy_date', models.DateTimeField(help_text=b'Datetime when copy was made.', auto_now_add=True)),
                ('original_series_id', models.ForeignKey(help_text=b'Original id of the series.', to='editorial.Series')),
                ('partner', models.ForeignKey(help_text=b'Organization that made the copy.', to='editorial.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='SeriesNote',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('text', models.TextField(help_text=b'Content of the note', blank=True)),
                ('creation_date', models.DateTimeField(help_text=b'When the note was created.', auto_now_add=True)),
                ('owner', models.ForeignKey(related_name='seriesnote_owner', to=settings.AUTH_USER_MODEL)),
                ('series', models.ForeignKey(related_name='Se', to='editorial.Series')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(help_text=b'The name by which the story is identified', max_length=250)),
                ('story_description', models.TextField(help_text=b'Short description of a story.', blank=True)),
                ('embargo', models.BooleanField(default=False, help_text=b'Is a story embargoed?')),
                ('embargo_datetime', models.DateTimeField(help_text=b'When is the story no longer under embargo.', null=True, blank=True)),
                ('creation_date', models.DateTimeField(help_text=b'When was the story created.', auto_now_add=True)),
                ('sensitive', models.BooleanField(default=False, help_text=b'Is a story sensitive and viewing it limited only to the team working on it?')),
                ('share', models.BooleanField(default=False, help_text=b'The story is being shared with a network.')),
                ('ready_to_share', models.BooleanField(default=False, help_text=b'The story is finished and ready to be copied.')),
                ('collaborate', models.BooleanField(default=False, help_text=b'The story is being collaborated on with a network.')),
                ('archived', models.BooleanField(default=False, help_text=b'Is the content no longer active and needed?')),
                ('collaborate_with', models.ManyToManyField(help_text=b'Network ids that a story is open to collaboration with.', related_name='story_collaborated_with_network', to='editorial.Network', blank=True)),
                ('owner', models.ForeignKey(related_name='story_owner', to=settings.AUTH_USER_MODEL, help_text=b'User who created the story')),
                ('series', models.ForeignKey(blank=True, to='editorial.Series', null=True)),
                ('share_with', models.ManyToManyField(help_text=b'Network ids that a story is shared with.', related_name='story_shared_with_network', to='editorial.Network', blank=True)),
                ('team', models.ManyToManyField(help_text=b'User contributing to the story.', related_name='story_team_member', to=settings.AUTH_USER_MODEL, blank=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
            },
        ),
        migrations.CreateModel(
            name='StoryCopyDetail',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('partner_story_id', models.SlugField(help_text=b"Id of the story on the copying organization's site.", max_length=15)),
                ('copy_date', models.DateTimeField(help_text=b'Datetime when copy was made.', auto_now_add=True)),
                ('original_story_id', models.ForeignKey(help_text=b'Original id of the story.', to='editorial.Story')),
                ('partner', models.ForeignKey(help_text=b'Organization that made the copy.', to='editorial.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='StoryNote',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('text', models.TextField(help_text=b'Content of the note', blank=True)),
                ('creation_date', models.DateTimeField(help_text=b'When the note was created.', auto_now_add=True)),
                ('owner', models.ForeignKey(related_name='storynote_owner', to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(to='editorial.Story')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserNote',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('text', models.TextField(help_text=b'Content of the note', blank=True)),
                ('creation_date', models.DateTimeField(help_text=b'When the note was created.', auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('keywords', django.contrib.postgres.fields.ArrayField(default=list, help_text=b'List of keywords for search.', base_field=models.CharField(max_length=100), size=None)),
                ('owner', models.ForeignKey(related_name='usernote_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoFacet',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(help_text=b'Unique code as needed for ingest sytems. Use as needed', max_length=75, blank=True)),
                ('title', models.TextField(help_text=b'Headline of the videofacet.')),
                ('excerpt', models.TextField(help_text=b'Excerpt from the videofacet.', blank=True)),
                ('vf_description', models.TextField(help_text=b'Description of the videofacet.', blank=True)),
                ('content', models.TextField(help_text=b'Content of the videofacet.', blank=True)),
                ('length', models.IntegerField(help_text=b'Wordcount of the videofacet.', blank=True)),
                ('keywords', django.contrib.postgres.fields.ArrayField(default=list, help_text=b'List of keywords for search.', base_field=models.CharField(max_length=100), size=None)),
                ('status', models.CharField(help_text=b'Videofacet status choice.', max_length=25, choices=[(b'DRFT', b'Draft'), (b'PT', b'Pitch'), (b'IP', b'In Progress'), (b'EDT', b'Edit'), (b'RVN', b'Revision'), (b'RDY', b'Ready')])),
                ('due_edit', models.DateTimeField(help_text=b'Due for edit.', blank=True)),
                ('run_date', models.DateTimeField(help_text=b'Planned run date.', blank=True)),
                ('creation_date', models.DateTimeField(help_text=b'Day videofacet was created.', auto_now_add=True)),
                ('share_note', models.TextField(help_text=b'Information for organizations making a copy of the videofacet.', blank=True)),
                ('assets', models.ManyToManyField(to='editorial.Asset')),
            ],
            options={
                'ordering': ['creation_date'],
                'verbose_name': 'Videofacet',
                'verbose_name_plural': 'Videofacets',
            },
        ),
        migrations.CreateModel(
            name='VideoFacetContributor',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('user_role', models.CharField(help_text=b'What did the user do?', max_length=255)),
                ('user', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
                ('videofacet', models.ForeignKey(to='editorial.VideoFacet')),
            ],
        ),
        migrations.CreateModel(
            name='VideoFacetCopyDetail',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('new_videofacet_id', models.SlugField(help_text=b"Id of the story on the copying organization's site.", max_length=15)),
                ('copy_date', models.DateTimeField(help_text=b'Datetime when copy was made.', auto_now_add=True)),
                ('original_videofacet_id', models.ForeignKey(help_text=b'Original id of the story.', to='editorial.VideoFacet')),
                ('partner', models.ForeignKey(help_text=b'Organization that made the copy.', to='editorial.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='WebFacet',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(help_text=b'Unique code as needed for ingest sytems. Use as needed', max_length=75, blank=True)),
                ('title', models.TextField(help_text=b'Headline of the Webfacet')),
                ('excerpt', models.TextField(help_text=b'Excerpt from the Webfacet.', blank=True)),
                ('wf_description', models.TextField(help_text=b'Description of the WebFacet.', blank=True)),
                ('content', models.TextField(help_text=b'Content of the webFacet.', blank=True)),
                ('length', models.IntegerField(help_text=b'Wordcount of the WebFacet.', blank=True)),
                ('keywords', django.contrib.postgres.fields.ArrayField(default=list, help_text=b'List of keywords for search.', size=None, base_field=models.CharField(max_length=100), blank=True)),
                ('status', models.CharField(help_text=b'WebFacet status choice.', max_length=25, choices=[(b'DRFT', b'Draft'), (b'PT', b'Pitch'), (b'IP', b'In Progress'), (b'EDT', b'Edit'), (b'RVN', b'Revision'), (b'RDY', b'Ready')])),
                ('due_edit', models.DateTimeField(help_text=b'Due for edit.', blank=True)),
                ('run_date', models.DateTimeField(help_text=b'Planned run date.', blank=True)),
                ('creation_date', models.DateTimeField(help_text=b'Day WebFacet was created.', auto_now_add=True)),
                ('share_note', models.TextField(help_text=b'Information for organizations making a copy of the webfacet.', blank=True)),
                ('assets', models.ManyToManyField(to='editorial.Asset')),
            ],
            options={
                'ordering': ['creation_date'],
                'verbose_name': 'Webfacet',
                'verbose_name_plural': 'Webfacets',
            },
        ),
        migrations.CreateModel(
            name='WebFacetContributor',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('user_role', models.CharField(help_text=b'What did the user do?', max_length=255)),
                ('user', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
                ('webfacet', models.ForeignKey(to='editorial.WebFacet')),
            ],
        ),
        migrations.CreateModel(
            name='WebFacetCopyDetail',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('new_webfacet_id', models.SlugField(help_text=b"Id of the story on the copying organization's site.", max_length=15)),
                ('copy_date', models.DateTimeField(help_text=b'Datetime when copy was made.', auto_now_add=True)),
                ('original_webfacet_id', models.ForeignKey(help_text=b'Original id of the story.', to='editorial.WebFacet')),
                ('partner', models.ForeignKey(help_text=b'Organization that made the copy.', to='editorial.Organization')),
            ],
        ),
        migrations.AddField(
            model_name='webfacet',
            name='contributors',
            field=models.ManyToManyField(help_text=b'Users that contributed to a facet. Used to associate multiple users to a facet.', to=settings.AUTH_USER_MODEL, through='editorial.WebFacetContributor'),
        ),
        migrations.AddField(
            model_name='webfacet',
            name='credit',
            field=models.ManyToManyField(help_text=b'The full user name(s) to be listed as the credit for the facet.', related_name='webfacetcredit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webfacet',
            name='discussion',
            field=models.ForeignKey(help_text=b'Id of edit discussion for the webfacet.', to='editorial.Discussion'),
        ),
        migrations.AddField(
            model_name='webfacet',
            name='editor',
            field=models.ForeignKey(related_name='webfaceteditor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webfacet',
            name='original_org',
            field=models.ForeignKey(to='editorial.Organization'),
        ),
        migrations.AddField(
            model_name='webfacet',
            name='owner',
            field=models.ForeignKey(related_name='webfacetowner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webfacet',
            name='story',
            field=models.ForeignKey(to='editorial.Story'),
        ),
        migrations.AddField(
            model_name='videofacet',
            name='contributors',
            field=models.ManyToManyField(help_text=b'Users that contributed to a facet. Used to associate multiple users to a facet.', to=settings.AUTH_USER_MODEL, through='editorial.VideoFacetContributor'),
        ),
        migrations.AddField(
            model_name='videofacet',
            name='credit',
            field=models.ManyToManyField(help_text=b'The full user name(s) to be listed as the credit for the facet.', related_name='videofacetcredit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videofacet',
            name='discussion',
            field=models.ForeignKey(help_text=b'ID of edit discussion for the videofacet.', to='editorial.Discussion'),
        ),
        migrations.AddField(
            model_name='videofacet',
            name='editor',
            field=models.ForeignKey(related_name='videofaceteditor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videofacet',
            name='original_org',
            field=models.ForeignKey(to='editorial.Organization'),
        ),
        migrations.AddField(
            model_name='videofacet',
            name='owner',
            field=models.ForeignKey(related_name='videofacetowner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videofacet',
            name='story',
            field=models.ForeignKey(to='editorial.Story'),
        ),
        migrations.AddField(
            model_name='printfacet',
            name='contributors',
            field=models.ManyToManyField(help_text=b'Users that contributed to a facet. Used to associate multiple users to a facet.', to=settings.AUTH_USER_MODEL, through='editorial.PrintFacetContributor'),
        ),
        migrations.AddField(
            model_name='printfacet',
            name='credit',
            field=models.ManyToManyField(help_text=b'The full user name(s) to be listed as the credit for the facet.', related_name='printfacetcredit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='printfacet',
            name='discussion',
            field=models.ForeignKey(help_text=b'Id of edit discussion for the printfacet.', to='editorial.Discussion'),
        ),
        migrations.AddField(
            model_name='printfacet',
            name='editor',
            field=models.ForeignKey(related_name='printfaceteditor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='printfacet',
            name='original_org',
            field=models.ForeignKey(to='editorial.Organization'),
        ),
        migrations.AddField(
            model_name='printfacet',
            name='owner',
            field=models.ForeignKey(related_name='printfacetowner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='printfacet',
            name='story',
            field=models.ForeignKey(to='editorial.Story'),
        ),
        migrations.AddField(
            model_name='networkorganization',
            name='organization',
            field=models.ForeignKey(to='editorial.Organization'),
        ),
        migrations.AddField(
            model_name='network',
            name='members',
            field=models.ManyToManyField(related_name='network_organization', through='editorial.NetworkOrganization', to='editorial.Organization'),
        ),
        migrations.AddField(
            model_name='network',
            name='owner_organization',
            field=models.ForeignKey(help_text=b'Organization that owns the network.', to='editorial.Organization'),
        ),
        migrations.AddField(
            model_name='historicalwebfacet',
            name='original_org',
            field=models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='editorial.Organization', null=True),
        ),
        migrations.AddField(
            model_name='historicalwebfacet',
            name='owner',
            field=models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AddField(
            model_name='historicalwebfacet',
            name='story',
            field=models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='editorial.Story', null=True),
        ),
        migrations.AddField(
            model_name='historicalvideofacet',
            name='original_org',
            field=models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='editorial.Organization', null=True),
        ),
        migrations.AddField(
            model_name='historicalvideofacet',
            name='owner',
            field=models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AddField(
            model_name='historicalvideofacet',
            name='story',
            field=models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='editorial.Story', null=True),
        ),
        migrations.AddField(
            model_name='historicalprintfacet',
            name='original_org',
            field=models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='editorial.Organization', null=True),
        ),
        migrations.AddField(
            model_name='historicalprintfacet',
            name='owner',
            field=models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AddField(
            model_name='historicalprintfacet',
            name='story',
            field=models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='editorial.Story', null=True),
        ),
        migrations.AddField(
            model_name='historicalaudiofacet',
            name='original_org',
            field=models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='editorial.Organization', null=True),
        ),
        migrations.AddField(
            model_name='historicalaudiofacet',
            name='owner',
            field=models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AddField(
            model_name='historicalaudiofacet',
            name='story',
            field=models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='editorial.Story', null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='discussion',
            field=models.ForeignKey(to='editorial.Discussion'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audiofacetcopydetail',
            name='partner',
            field=models.ForeignKey(help_text=b'Organization that made the copy.', to='editorial.Organization'),
        ),
        migrations.AddField(
            model_name='audiofacet',
            name='contributors',
            field=models.ManyToManyField(help_text=b'Users that contributed to a facet. Used to associate multiple users to a facet.', to=settings.AUTH_USER_MODEL, through='editorial.AudioFacetContributor'),
        ),
        migrations.AddField(
            model_name='audiofacet',
            name='credit',
            field=models.ManyToManyField(help_text=b'The full user name(s) to be listed as the credit for the facet.', related_name='audiofacetcredit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audiofacet',
            name='discussion',
            field=models.ForeignKey(help_text=b'Id of edit discussion for the audiofacet.', to='editorial.Discussion'),
        ),
        migrations.AddField(
            model_name='audiofacet',
            name='editor',
            field=models.ForeignKey(related_name='audiofaceteditor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audiofacet',
            name='original_org',
            field=models.ForeignKey(to='editorial.Organization'),
        ),
        migrations.AddField(
            model_name='audiofacet',
            name='owner',
            field=models.ForeignKey(related_name='audiofacetowner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audiofacet',
            name='story',
            field=models.ForeignKey(to='editorial.Story'),
        ),
        migrations.AddField(
            model_name='user',
            name='notes',
            field=models.ManyToManyField(related_name='user_note', to='editorial.UserNote'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, to='editorial.Organization', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(related_query_name='user', related_name='user_set', to='auth.Permission', blank=True, help_text='Specific permissions for this user.', verbose_name='user permissions'),
        ),
    ]
