# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0001_cleansweep'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='network',
            options={'ordering': ['name'], 'verbose_name': 'Network', 'verbose_name_plural': 'Networks'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['name'], 'verbose_name': 'Series', 'verbose_name_plural': 'Series'},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['name'], 'verbose_name': 'Story', 'verbose_name_plural': 'Stories'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['credit_name'], 'verbose_name': 'Team member', 'verbose_name_plural': 'Team members'},
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='asset_attribution',
            new_name='attribution',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='asset_creation_date',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='asset_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='asset_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='asset_owner',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='asset_s3_link',
            new_name='s3_link',
        ),
        migrations.RenameField(
            model_name='audiofacet',
            old_name='audiofacet_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='audiofacetcontributor',
            old_name='audiofacet_contributor_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='audiofacetcopydetail',
            old_name='copy_details_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='commentreadstatus',
            old_name='read_status_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='discussion',
            old_name='discussion_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='historicalaudiofacet',
            old_name='audiofacet_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='historicalprintfacet',
            old_name='printfacet_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='historicalvideofacet',
            old_name='videofacet_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='historicalwebfacet',
            old_name='webfacet_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='network',
            old_name='network_creation_date',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='network',
            old_name='network_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='network',
            old_name='network_logo',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='network',
            old_name='network_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='network',
            old_name='network_owner_organization',
            new_name='owner_organization',
        ),
        migrations.RenameField(
            model_name='networkorganizaton',
            old_name='network_organization_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='organization_creation_date',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='organization_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='organization_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='organization_owner',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='printfacet',
            old_name='printfacet_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='printfacetcontributor',
            old_name='printfacet_contributor_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='printfacetcopydetail',
            old_name='copy_details_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='privatediscussion',
            old_name='private_discussion_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='series_creation_date',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='series_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='series_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='series_owner',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='series_team',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='seriescopydetail',
            old_name='copy_details_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='seriesplan',
            old_name='series_planning_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='seriesplan',
            old_name='series_plan_note',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='seriesplan',
            old_name='series_plan_note_owner',
            new_name='note_owner',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='story_creation_date',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='story_embargo',
            new_name='embargo',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='story_embargo_datetime',
            new_name='embargo_datetime',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='story_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='story_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='story_owner',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='story_sensitivity',
            new_name='sensitivity',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='story_team',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='storycopydetail',
            old_name='copy_details_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='storyplan',
            old_name='story_planning_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='storyplan',
            old_name='story_plan_note',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='storyplan',
            old_name='story_plan_note_owner',
            new_name='note_owner',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_credit_name',
            new_name='credit_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_expertise',
            new_name='expertise',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_facebook',
            new_name='facebook',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_fname',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_instagram',
            new_name='instagram',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_linkedin',
            new_name='linkedin',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_lname',
            new_name='lname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_organization_id',
            new_name='organization_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_snapchat',
            new_name='snapchat',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_twitter',
            new_name='twitter',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_vine',
            new_name='vine',
        ),
        migrations.RenameField(
            model_name='videofacet',
            old_name='videofacet_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='videofacetcontributor',
            old_name='videofacet_contributor_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='videofacetcopydetail',
            old_name='copy_details_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='webfacet',
            old_name='webfacet_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='webfacetcontributor',
            old_name='webfacet_contributor_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='webfacetcopydetail',
            old_name='copy_details_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='network',
            name='network_description',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='organization_description',
        ),
        migrations.RemoveField(
            model_name='series',
            name='series_description',
        ),
        migrations.RemoveField(
            model_name='story',
            name='story_description',
        ),
        migrations.AlterField(
            model_name='audiofacetcopydetail',
            name='original_audiofacet_id',
            field=models.ForeignKey(help_text=b'Original id of the story.', to='editorial.AudioFacet'),
        ),
        migrations.AlterField(
            model_name='printfacetcopydetail',
            name='original_printfacet_id',
            field=models.ForeignKey(help_text=b'Original id of the story.', to='editorial.PrintFacet'),
        ),
        migrations.AlterField(
            model_name='storycopydetail',
            name='original_story_id',
            field=models.ForeignKey(help_text=b'Original id of the story.', to='editorial.Story'),
        ),
        migrations.AlterField(
            model_name='videofacetcopydetail',
            name='original_videofacet_id',
            field=models.ForeignKey(help_text=b'Original id of the story.', to='editorial.VideoFacet'),
        ),
        migrations.AlterField(
            model_name='webfacetcopydetail',
            name='original_webfacet_id',
            field=models.ForeignKey(help_text=b'Original id of the story.', to='editorial.WebFacet'),
        ),
    ]
