# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0070_auto_20171211_0330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofacet',
            name='audio_assets',
        ),
        migrations.RemoveField(
            model_name='audiofacet',
            name='contributors',
        ),
        migrations.RemoveField(
            model_name='audiofacet',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='audiofacet',
            name='discussion',
        ),
        migrations.RemoveField(
            model_name='audiofacet',
            name='document_assets',
        ),
        migrations.RemoveField(
            model_name='audiofacet',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='audiofacet',
            name='image_assets',
        ),
        migrations.RemoveField(
            model_name='audiofacet',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='audiofacet',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='audiofacet',
            name='story',
        ),
        migrations.RemoveField(
            model_name='audiofacet',
            name='video_assets',
        ),
        migrations.RemoveField(
            model_name='audiofacetcontributor',
            name='audiofacet',
        ),
        migrations.RemoveField(
            model_name='audiofacetcontributor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='audiofacetcopydetail',
            name='original_audiofacet',
        ),
        migrations.RemoveField(
            model_name='audiofacetcopydetail',
            name='original_org',
        ),
        migrations.RemoveField(
            model_name='audiofacetcopydetail',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='audiofacetcopydetail',
            name='partner_audiofacet',
        ),
        migrations.RemoveField(
            model_name='historicalaudiofacet',
            name='discussion',
        ),
        migrations.RemoveField(
            model_name='historicalaudiofacet',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='historicalaudiofacet',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalaudiofacet',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='historicalaudiofacet',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='historicalaudiofacet',
            name='story',
        ),
        migrations.RemoveField(
            model_name='historicalprintfacet',
            name='discussion',
        ),
        migrations.RemoveField(
            model_name='historicalprintfacet',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='historicalprintfacet',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalprintfacet',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='historicalprintfacet',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='historicalprintfacet',
            name='story',
        ),
        migrations.RemoveField(
            model_name='historicalvideofacet',
            name='discussion',
        ),
        migrations.RemoveField(
            model_name='historicalvideofacet',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='historicalvideofacet',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalvideofacet',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='historicalvideofacet',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='historicalvideofacet',
            name='story',
        ),
        migrations.RemoveField(
            model_name='historicalwebfacet',
            name='discussion',
        ),
        migrations.RemoveField(
            model_name='historicalwebfacet',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='historicalwebfacet',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalwebfacet',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='historicalwebfacet',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='historicalwebfacet',
            name='story',
        ),
        migrations.RemoveField(
            model_name='printfacet',
            name='audio_assets',
        ),
        migrations.RemoveField(
            model_name='printfacet',
            name='contributors',
        ),
        migrations.RemoveField(
            model_name='printfacet',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='printfacet',
            name='discussion',
        ),
        migrations.RemoveField(
            model_name='printfacet',
            name='document_assets',
        ),
        migrations.RemoveField(
            model_name='printfacet',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='printfacet',
            name='image_assets',
        ),
        migrations.RemoveField(
            model_name='printfacet',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='printfacet',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='printfacet',
            name='story',
        ),
        migrations.RemoveField(
            model_name='printfacet',
            name='video_assets',
        ),
        migrations.RemoveField(
            model_name='printfacetcontributor',
            name='printfacet',
        ),
        migrations.RemoveField(
            model_name='printfacetcontributor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='printfacetcopydetail',
            name='original_org',
        ),
        migrations.RemoveField(
            model_name='printfacetcopydetail',
            name='original_printfacet',
        ),
        migrations.RemoveField(
            model_name='printfacetcopydetail',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='printfacetcopydetail',
            name='partner_printfacet',
        ),
        migrations.RemoveField(
            model_name='videofacet',
            name='audio_assets',
        ),
        migrations.RemoveField(
            model_name='videofacet',
            name='contributors',
        ),
        migrations.RemoveField(
            model_name='videofacet',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='videofacet',
            name='discussion',
        ),
        migrations.RemoveField(
            model_name='videofacet',
            name='document_assets',
        ),
        migrations.RemoveField(
            model_name='videofacet',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='videofacet',
            name='image_assets',
        ),
        migrations.RemoveField(
            model_name='videofacet',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='videofacet',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='videofacet',
            name='story',
        ),
        migrations.RemoveField(
            model_name='videofacet',
            name='video_assets',
        ),
        migrations.RemoveField(
            model_name='videofacetcontributor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='videofacetcontributor',
            name='videofacet',
        ),
        migrations.RemoveField(
            model_name='videofacetcopydetail',
            name='original_org',
        ),
        migrations.RemoveField(
            model_name='videofacetcopydetail',
            name='original_videofacet',
        ),
        migrations.RemoveField(
            model_name='videofacetcopydetail',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='videofacetcopydetail',
            name='partner_videofacet',
        ),
        migrations.RemoveField(
            model_name='webfacet',
            name='audio_assets',
        ),
        migrations.RemoveField(
            model_name='webfacet',
            name='contributors',
        ),
        migrations.RemoveField(
            model_name='webfacet',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='webfacet',
            name='discussion',
        ),
        migrations.RemoveField(
            model_name='webfacet',
            name='document_assets',
        ),
        migrations.RemoveField(
            model_name='webfacet',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='webfacet',
            name='image_assets',
        ),
        migrations.RemoveField(
            model_name='webfacet',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='webfacet',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='webfacet',
            name='story',
        ),
        migrations.RemoveField(
            model_name='webfacet',
            name='video_assets',
        ),
        migrations.RemoveField(
            model_name='webfacetcontributor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='webfacetcontributor',
            name='webfacet',
        ),
        migrations.RemoveField(
            model_name='webfacetcopydetail',
            name='original_org',
        ),
        migrations.RemoveField(
            model_name='webfacetcopydetail',
            name='original_webfacet',
        ),
        migrations.RemoveField(
            model_name='webfacetcopydetail',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='webfacetcopydetail',
            name='partner_webfacet',
        ),
        migrations.DeleteModel(
            name='AudioFacet',
        ),
        migrations.DeleteModel(
            name='AudioFacetContributor',
        ),
        migrations.DeleteModel(
            name='AudioFacetCopyDetail',
        ),
        migrations.DeleteModel(
            name='HistoricalAudioFacet',
        ),
        migrations.DeleteModel(
            name='HistoricalPrintFacet',
        ),
        migrations.DeleteModel(
            name='HistoricalVideoFacet',
        ),
        migrations.DeleteModel(
            name='HistoricalWebFacet',
        ),
        migrations.DeleteModel(
            name='PrintFacet',
        ),
        migrations.DeleteModel(
            name='PrintFacetContributor',
        ),
        migrations.DeleteModel(
            name='PrintFacetCopyDetail',
        ),
        migrations.DeleteModel(
            name='VideoFacet',
        ),
        migrations.DeleteModel(
            name='VideoFacetContributor',
        ),
        migrations.DeleteModel(
            name='VideoFacetCopyDetail',
        ),
        migrations.DeleteModel(
            name='WebFacet',
        ),
        migrations.DeleteModel(
            name='WebFacetContributor',
        ),
        migrations.DeleteModel(
            name='WebFacetCopyDetail',
        ),
    ]
