# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-26 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0086_auto_20180102_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='network_invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='editorial.Network'),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='network_invitation_response',
            field=models.NullBooleanField(),
        ),
    ]
