# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-12 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0087_auto_20180226_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='share',
        ),
        migrations.RemoveField(
            model_name='project',
            name='share_with',
        ),
        migrations.RemoveField(
            model_name='project',
            name='share_with_date',
        ),
        migrations.RemoveField(
            model_name='series',
            name='share',
        ),
        migrations.RemoveField(
            model_name='series',
            name='share_with',
        ),
        migrations.RemoveField(
            model_name='series',
            name='share_with_date',
        ),
        migrations.AddField(
            model_name='network',
            name='simple_audio_assets',
            field=models.ManyToManyField(blank=True, to='editorial.SimpleAudio'),
        ),
        migrations.AddField(
            model_name='network',
            name='simple_document_assets',
            field=models.ManyToManyField(blank=True, to='editorial.SimpleDocument'),
        ),
        migrations.AddField(
            model_name='network',
            name='simple_image_assets',
            field=models.ManyToManyField(blank=True, to='editorial.SimpleImage'),
        ),
        migrations.AddField(
            model_name='network',
            name='simple_video_assets',
            field=models.ManyToManyField(blank=True, to='editorial.SimpleVideo'),
        ),
        migrations.AddField(
            model_name='organization',
            name='simple_audio_assets',
            field=models.ManyToManyField(blank=True, related_name='organization_simple_audio', to='editorial.SimpleAudio'),
        ),
        migrations.AddField(
            model_name='organization',
            name='simple_document_assets',
            field=models.ManyToManyField(blank=True, related_name='organization_simple_document', to='editorial.SimpleDocument'),
        ),
        migrations.AddField(
            model_name='organization',
            name='simple_image_assets',
            field=models.ManyToManyField(blank=True, related_name='organization_simple_image', to='editorial.SimpleImage'),
        ),
        migrations.AddField(
            model_name='organization',
            name='simple_video_assets',
            field=models.ManyToManyField(blank=True, related_name='organization_simple_video', to='editorial.SimpleVideo'),
        ),
        migrations.AddField(
            model_name='series',
            name='series_logo',
            field=models.ImageField(blank=True, upload_to=b'series'),
        ),
        migrations.AddField(
            model_name='user',
            name='name_pronunciation',
            field=models.TextField(blank=True, help_text=b'Instruction on the proper pronunciation of the users name.'),
        ),
        migrations.AddField(
            model_name='user',
            name='pronoun',
            field=models.CharField(blank=True, help_text=b'Users preferred pronoun.', max_length=50),
        ),
    ]
