# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-13 01:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0091_auto_20190512_1710'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrganizationDiscoveryProfile',
            new_name='OrganizationPublicProfile',
        ),
        migrations.AlterModelOptions(
            name='organizationpublicprofile',
            options={'verbose_name': 'Public Profile', 'verbose_name_plural': 'Public Profiles'},
        ),
    ]
