# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-13 01:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0092_auto_20190512_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationpublicprofile',
            name='organization',
        ),
        migrations.AddField(
            model_name='organization',
            name='public_profile',
            field=models.ForeignKey(blank=True, help_text=b'ID of public profile for an organization', null=True, on_delete=django.db.models.deletion.CASCADE, to='editorial.OrganizationPublicProfile'),
        ),
    ]
