# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-13 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0094_auto_20190512_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationpublicprofile',
            options={'verbose_name': 'Organization Public Profile', 'verbose_name_plural': 'Organization Public Profiles'},
        ),
        migrations.AlterField(
            model_name='organization',
            name='public_profile',
            field=models.OneToOneField(blank=True, help_text=b'ID of public profile for an organization', null=True, on_delete=django.db.models.deletion.CASCADE, to='editorial.OrganizationPublicProfile'),
        ),
    ]
