# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-15 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0095_auto_20190512_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationpublicprofile',
            name='seeking_collabs',
            field=models.BooleanField(default=False, help_text=b'Actively seeking collaborative projects to participate in.'),
        ),
        migrations.AddField(
            model_name='organizationpublicprofile',
            name='seeking_partners',
            field=models.BooleanField(default=False, help_text=b'Actively seeking partners for a specific project.'),
        ),
    ]
