# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-15 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0097_organization_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='cover_photo',
            field=models.ImageField(blank=True, upload_to=b'org_covers'),
        ),
    ]
